version: "3.9"
services:
  xui:
    image: enwaiax/x-ui
    container_name: xui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "5244:5244"
      - "1000:1000"
      - "555:555"
      - "556:556"
      - "54321:54321"
